### ISSUE TITLE
Count how many toots since a start date

### ISSUE THREAD

**Issue by OwainWilliams** [H5YR/High5YouRock#24]
Let's had a count to show how many toots have been made since a date e.g 1st October. 

We could add a table in the database that just keeps a count of how many toots have been made since the code has been implemented.

**Comment by abjerner** [comment]
I think the approach to this could be something:

1. fetch all statuses from the `#h5yr` hash tag (or from the 1st of October)
2. save count in database
3. save ID of the most recent status
4. fetch new statuses by specifying `min_id`
5. add length of new statuses to the overall status count and save to the database
6. save ID of the most recent status
7. repeat from 4.

My **Skybrud.Social.Mastodon** package, which is used for communicating with the API, should support pagination via either `max_id` or `min_id`.

Statuses may be deleted over time, so maybe this should be repeated from 1-7 once in a while. Or maybe it's fine counting deleted statuses. Over time the list of statuses will grow, and we may hit some rate limits.

Alternatively the status count could be within the last 31 days or something - opposed to tracking since a given date.
